# Assumes podman-compose.
# This is especially relevant for networking.

services:
  caddy-ca:
    container_name: caddy-ca
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,Z
      - ./caddy_data:/data:z
      - ./caddy_config:/config:Z
    expose:
      - "2019" # For ACME

  caddy-leaf:
    networks:
      default:
        aliases:
          # Overrides `leaf.localhost' for the podman network.
          #
          # The host machine, however, resolves it to 127.0.0.1.
          # Thus, leaf.localhost:8000 resolves to this container as long as the port is mapped.
          - leaf.localhost # ACME certificate requires a domain name with a "."
    build:
      context: .
      dockerfile: ./caddy-leaf/Dockerfile
    container_name: caddy-leaf
    restart: unless-stopped
    volumes:
      - ./caddy-leaf/Caddyfile:/etc/caddy/Caddyfile:ro,Z
      - ./caddy-leaf/site:/srv:Z
      - ./caddy-leaf/caddy_data:/data:Z
      - ./caddy-leaf/caddy_config:/config:Z
      - ./caddy_data/caddy/pki/authorities/local/root.crt:/etc/caddy/root.crt:ro,z
    ports:
      - "8000:443" # HTTPS leaf exposed
    expose:
      - "80"  # For ACME's http-01 challenge
      - "443" # For serving a website with HTTPS

