services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "8443:443"
      - "8443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      - ./site:/srv:Z
      - ./caddy_data:/data:Z
      - ./caddy_config:/config:Z
