# Assumes podman-compose.
# This is especially relevant for networking.

services:
  caddy_acme:
    container_name: caddy_acme
    restart: unless-stopped
    build:
      dockerfile: ./caddy_acme/Dockerfile
    volumes:
      - ./caddy_acme/Caddyfile:/etc/caddy/Caddyfile:ro,Z
      - ./caddy_acme/caddy_data:/data:z
      - ./caddy_acme/caddy_config:/config:Z
    expose:
      - "2019" # For ACME
    networks:
      - sharednet


networks:
  sharednet:
    external: true
    name: local_acme_net

