# Assumes podman-compose.
# This is especially relevant for networking.

services:
  caddy_ca:
    container_name: caddy_ca
    restart: unless-stopped
    build:
      dockerfile: ./caddy_ca/Dockerfile
    volumes:
      - ./caddy_ca/Caddyfile:/etc/caddy/Caddyfile:ro,Z
      - ./caddy_ca/caddy_data:/data:z
      - ./caddy_ca/caddy_config:/config:Z
    expose:
      - "2019" # For ACME

  caddy_leaf:
    networks:
      default:
        aliases:
          # Overrides the hostname for the podman network.
          #
          # The host machine, however, resolves it to 127.0.0.1.
          # Thus, leaf.localhost:8000 resolves to this container as long as the port is mapped.
          - leaf.localhost # ACME certificate requires a domain name with a "."
    build:
      dockerfile: ./caddy_leaf/Dockerfile
    container_name: caddy_leaf
    restart: unless-stopped
    volumes:
      - ./caddy_leaf/Caddyfile:/etc/caddy/Caddyfile:ro,Z
      - ./caddy_leaf/site:/srv:Z
      - ./caddy_leaf/caddy_data:/data:Z
      - ./caddy_leaf/caddy_config:/config:Z
      - ./caddy_ca/caddy_data/caddy/pki/authorities/local/root.crt:/etc/caddy/root.crt:ro,z
    ports:
      - "8000:443" # HTTPS leaf exposed
    expose:
      - "80"  # For ACME's http-01 challenge
      - "443" # For serving a website with HTTPS

