services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
      - "8443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./site:/srv
      - ./caddy_data:/data
      - ./caddy_config:/config
