services:
  caddy_leaf:
    networks:
      sharednet:
        aliases:
          - leaf.localhost # ACME requires the client HTTPS server to have a domain name with a ".".
          # This container is exposed as `leaf.localhost` inside the podman network.
          #
          # The host machine, however, resolves it to 127.0.0.1.
          # Thus, `leaf.localhost:8000` resolves to this container as long as the port is mapped.
          # In this way, you can access this container without adding it to the hostname database of the host machine (like by editing `/etc/hosts`).
    build:
      dockerfile: Dockerfile
    container_name: caddy_leaf
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,Z
      - ./site:/srv:Z
      - ./caddy_data:/data:Z
      - ./caddy_config:/config:Z
      - ../caddy_acme/caddy_data/caddy/pki/authorities/local/root.crt:/etc/caddy/root.crt:ro,z
    ports:
      - "8000:443" # HTTPS leaf exposed
    expose:
      - "80"  # For ACME's http-01 challenge
      - "443" # For serving a website with HTTPS

networks:
  sharednet:
    external: true
    name: local_acme_net

